// This file is generated by the discover-tests script

#include "rs-core/unit-test.hpp"
#include <print>
#include <string>
#include <vector>

using namespace RS::UnitTest;

void test_rs_containers_ring_buffer_basic_queue_eject();
void test_rs_containers_ring_buffer_basic_queue_reject();
void test_rs_containers_ring_buffer_basic_stack_eject();
void test_rs_containers_ring_buffer_basic_stack_reject();
void test_rs_containers_ring_buffer_static_queue_eject();
void test_rs_containers_ring_buffer_static_queue_reject();
void test_rs_containers_ring_buffer_static_stack_eject();
void test_rs_containers_ring_buffer_static_stack_reject();
void test_rs_containers_version();

int main(int argc, char** argv) {

    main_args = std::vector<std::string>(argv + 1, argv + argc);
    std::println("");
    std::println("{}Running unit tests{}", xhead, xreset);
    std::println("{}{}{}", xrule, rule, xreset);

    call_me_maybe(test_rs_containers_ring_buffer_basic_queue_eject, "test_rs_containers_ring_buffer_basic_queue_eject");
    call_me_maybe(test_rs_containers_ring_buffer_basic_queue_reject, "test_rs_containers_ring_buffer_basic_queue_reject");
    call_me_maybe(test_rs_containers_ring_buffer_basic_stack_eject, "test_rs_containers_ring_buffer_basic_stack_eject");
    call_me_maybe(test_rs_containers_ring_buffer_basic_stack_reject, "test_rs_containers_ring_buffer_basic_stack_reject");
    call_me_maybe(test_rs_containers_ring_buffer_static_queue_eject, "test_rs_containers_ring_buffer_static_queue_eject");
    call_me_maybe(test_rs_containers_ring_buffer_static_queue_reject, "test_rs_containers_ring_buffer_static_queue_reject");
    call_me_maybe(test_rs_containers_ring_buffer_static_stack_eject, "test_rs_containers_ring_buffer_static_stack_eject");
    call_me_maybe(test_rs_containers_ring_buffer_static_stack_reject, "test_rs_containers_ring_buffer_static_stack_reject");
    call_me_maybe(test_rs_containers_version, "test_rs_containers_version");

    std::println("{}{}{}", xrule, rule, xreset);

    if (failures == 0) {
        std::println("{}OK - all tests passed{}", xpass, xreset);
    } else {
        std::println("{}*** Test failures: {}{}", xfail, failures, xreset);
    }

    std::println("");

    return failures;

}
